### ISSUE TITLE
Pagenatorの共通エレメント

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Blogs#15]
https://github.com/NetCommons3/Blogs/blob/master/View/BlogEntries/index.ctp#L138

共通のエレメントがあるようです。
https://github.com/NetCommons3/NetCommons/blob/master/View/Elements/paginator.ctp

**Comment by RyujiAMANO** [comment]
https://github.com/NetCommons3/NetCommons/issues/26

このIssueが解決したら組み込みます
