### ISSUE TITLE
編集権限処理問題

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Blogs#16]
https://github.com/NetCommons3/Blogs/blob/master/View/Elements/BlogEntries/edit_link.ctp

現状$statusがわたってきてない旨のNotice発生。
そもそも、こういう処理は共通ですね。
もくもく会で相談させてください。

**Comment by RyujiAMANO** [comment]
確かに渡してないけどnotice出てない…って調べてたら$contentPublishable権限あればステータスチェック通らないからか。
修正します。
