### ISSUE TITLE
SQL関数の使用について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Blogs#17]
BlogEntry::getYearMonthCount
で月ごとの投稿件数を取得するため、DATE_FORMAT関数を使用しています。
NC3はMySQL+Mroongaなので、SQL関数を使用しても良いかなと思っています。

関係者の意識合わせを含め、一応もくもく会で確認しときたいです。

**Comment by ryu818** [comment]
寺口さんへ。
SQLで「MATCH　AGAINST」をしているわけではないので
全文検索エンジンのストレージエンジン（Mroonga）は使用されないのではないでしょうか。
MySQLではなく他のDBを使用するというのであれば話しはわかります。
（Mroongaがはいっている段階でMariaDB等になるのでしょうが。）

**Comment by kteraguchi** [comment]
検索等でMATCH　AGAINSTを使用するはずです。
ですので、SQL関数を使用しても良いかなと思っています。

**Comment by RyujiAMANO** [comment]
使用OKって結論だったと思うのでクローズします
