### ISSUE TITLE
コンテンツ削除のガード

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/Blogs#19]
公開後のコンテンツを削除できるのは、公開権限のあるユーザのみ。（削除は承認フローとかないので）

現状だと一度でも公開されたら公開権限のないユーザは削除不可（現状だと公開後に新たな承認フローが走るとステータスが公開以外になるが、一度でも公開されてたら権限無い人はコンテンツ削除NG)
判定としてはis_activeが一度でもあったら、公開権限無いユーザは削除不可とすればOK.
- 削除ボタン表示条件を実装する
- 削除アクションのガードを実装する

**Comment by RyujiAMANO** [comment]
94533abdda961ec21d807875d60d1dda3d01a256 で対応

**Comment by kteraguchi** [comment]
確認したところ作成者は削除できる仕様とのことでした。
申し訳ないです。再度オープンします。

ただし、作成者ではないが、編集権限を持っている人は削除できるか再確認が必要。

**Comment by RyujiAMANO** [comment]
結局公開後の削除は公開権限必用ということで落ち着いたので、修正しない
