### ISSUE TITLE
ブロック一覧に説明文追加

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/Blogs#66]
文章どこのを参考にしたらいいんだろうな
FAQとかリンクリストがOKぽい

> ハイライトされているFAQが現在表示されています。
> 新しく作成するときは、 【プラスアイコン】を押してください。
> 編集もしくは削除するときは、 【編集アイコン】を押してください。

アイコンはglyph-icon。ハイライトはactive適用されてるかな
FAQ参照。
というかこれ共通か？

**Comment by akagane99** [comment]
共通ですね。
動画も対応しました。
