### ISSUE TITLE
メール設定で決定ボタン後→「正常に登録しました。」メッセージが表示されてない

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/Blogs#70]
https://docs.google.com/spreadsheets/d/1TjVLQA-xjRw-3Tfo5WkWge5Ka6veg1ZyBlpX5CgkMVo/edit#gid=1916061857

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Mails/commit/25951d61bd4428eb5d527ebf085a00860979a84f
共通で対応しました。

**Comment by RyujiAMANO** [comment]
おお！たすかります
